
$stderr.puts "fail"
$stderr.flush
#loop {}
